// © 2026 Reborn Vision — All rights reserved. Unauthorized copying, modification or distribution is strictly prohibited. https://reborn-vision.com
export default {
  nav: {
    docs: 'Documentation',
    manage: 'Manage subscription',
    install: 'Install for free'
  },
  hero: {
    badge: 'Real-time OCR translation',
    title: 'REBORN VISION',
    tagline: 'Translate any text on screen. In real time.',
    sub: 'Select a zone, press Ctrl+E — the translation appears instantly. Works on all websites, all games, all images.',
    cta_primary: 'Install for free',
    cta_secondary: 'View documentation',
    trust1: '5 translations/day free',
    trust2: 'No data stored',
    trust3: '15 OCR languages',
    store_name: 'Chrome Web Store',
    store_sub: 'Free extension',
    store_rating: '★★★★★'
  },
  features: {
    title: 'Everything you need',
    sub: 'An extension built for fluidity — translating should never interrupt your experience.',
    f1_title: 'Universal OCR',
    f1_desc: 'Captures and reads text from any screen zone: subtitles, game interfaces, PDFs, images. If it\'s displayed, Vision can read it.',
    f1_badge: 'All languages',
    f2_title: 'Instant translation',
    f2_desc: 'The translation bubble appears directly on your screen, in the right place, without leaving the page or opening a tab.',
    f2_badge: 'Frictionless',
    f3_title: 'Watch Mode',
    f3_desc: 'Activate watch mode on a zone — Vision re-translates automatically when the text changes. Perfect for live subtitles.',
    f3_badge: 'Premium',
    f4_title: 'Multi-zone',
    f4_desc: 'Define multiple capture zones simultaneously on the same page. Each zone has its own translation bubble.',
    f4_badge: 'Premium',
    f5_title: 'Customizable interface',
    f5_desc: '6 visual themes (MMO Gold, Cyber Blue, Neon Purple, Fire Red, Dark, White). Choose the one that fits your setup.',
    f5_badge: 'Free',
    f6_title: '15 interface languages',
    f6_desc: 'Vision\'s interface is available in 15 languages. Set it once, use it everywhere.',
    f6_badge: 'Free'
  },
  security: {
    title: 'Built for privacy',
    sub: 'Your screenshots are never stored. Images are processed in real time and immediately deleted.',
    s1_title: 'Secure authentication',
    s1_desc: 'Sign in via Google OAuth2. Short-lived JWT tokens, no passwords stored.',
    s2_title: 'Stripe payments',
    s2_desc: 'Transactions 100% handled by Stripe. We never see your card number.',
    s3_title: 'Zero tracking',
    s3_desc: 'No browsing history collected. No personal data sold or shared.',
    s4_title: 'Images never stored',
    s4_desc: 'Zone captures are processed in real time on our secure servers and immediately deleted after processing.'
  },
  pricing: {
    title: 'Choose your plan',
    sub: 'Start free. Go premium when you\'re ready.',
    popular: 'Popular',
    per_month: '/month',
    per_year: '/year',
    one_time: 'one-time payment',
    trial: '7-day free trial',
    cta_free: 'Start for free',
    cta_paid: 'Start trial',
    cta_lifetime: 'Get lifetime',
    voyageur: {
      rank: 'Voyager',
      price: '€0',
      f1: '5 translations per day',
      f2: '1 active zone',
      f3: '15 OCR languages',
      f4: '6 visual themes',
      f5: '15-language interface'
    },
    aventurier: {
      rank: 'Adventurer',
      price: '€2.99',
      f1: 'Unlimited translations',
      f2: 'Unlimited zones',
      f3: 'Automatic Watch Mode',
      f4: 'Priority support',
      f5: 'Early access to new features'
    },
    champion: {
      rank: 'Champion',
      price: '€24.99',
      save: 'Save 30%',
      f1: 'Unlimited translations',
      f2: 'Unlimited zones',
      f3: 'Automatic Watch Mode',
      f4: 'Priority support',
      f5: 'Early access to new features'
    },
    legende: {
      rank: 'Legend',
      price: '€99.99',
      f1: 'Unlimited lifetime translations',
      f2: 'Unlimited zones',
      f3: 'Automatic Watch Mode',
      f4: 'All future features',
      f5: 'Lifetime priority support'
    }
  },
  faq: {
    title: 'Frequently asked questions',
    q1: 'Does Vision work on all websites?',
    a1: 'Yes. Vision injects itself on all websites. If text is visible on screen, Vision can capture and translate it — even in browser games, PDFs, or images.',
    q2: 'How does OCR work?',
    a2: 'You select a zone with Ctrl+E, Vision captures that zone and sends it to our secure servers for text recognition (OCR). The translation is returned in under a second. Images are never stored.',
    q3: 'Can I cancel my subscription?',
    a3: 'Yes, at any time from the Stripe customer portal. Premium access is maintained until the end of the paid period. No hidden fees.',
    q4: 'Does the lifetime plan include future features?',
    a4: 'Yes. The Legend plan gives access to all current and future features, with no time limit.',
    q5: 'Is my data secure?',
    a5: 'Screenshots are processed in real time and never stored. Only your email and subscription status are kept in Firebase. No browsing data is collected.'
  },
  stats: {
    s1: '15 languages',
    s1_sub: 'Supported OCR languages',
    s2: '6 themes',
    s2_sub: 'Visual themes',
    s3: 'Real time',
    s3_sub: 'Instant translation',
    s4: '0 storage',
    s4_sub: 'Images never kept'
  },
  trust: {
    t1: 'Secure Stripe payment',
    t2: 'Cancel anytime',
    t3: '7-day free trial',
    t4: 'Responsive support'
  },
  footer: {
    tagline: 'Real-time OCR translation for Chrome.',
    docs: 'Documentation',
    legal: 'Legal notice',
    privacy: 'Privacy',
    contact: 'Contact',
    rights: '© 2026 Reborn Vision. All rights reserved.'
  },
  docs: {
    home_title: 'Documentation',
    home_sub: 'Everything you need to know to use Reborn Vision.',
    cat_user: 'User guide',
    cat_support: 'Support',
    cat_legal: 'Legal information',
    card_quickstart_title: 'Quick Start',
    card_quickstart_desc: 'Install Vision, select your first zone and make your first translation in 2 minutes.',
    card_features_title: 'Features',
    card_features_desc: 'Full Free vs Premium comparison. Watch Mode, multi-zone, shortcuts.',
    card_interface_title: 'Interface & Customization',
    card_interface_desc: 'Themes, languages, advanced settings, keyboard shortcuts.',
    card_troubleshooting_title: 'Troubleshooting',
    card_troubleshooting_desc: 'Common problems and solutions. Inaccurate OCR, zone not responding, etc.',
    card_privacy_title: 'Legal & Privacy',
    card_privacy_desc: 'Privacy policy, terms of use, GDPR, license.'
  },
  quickstart: {
    title: 'Quick Start',
    prereq_title: 'Prerequisites',
    prereq1: 'Chromium-based browser (Chrome, Edge, Brave...)',
    prereq2: 'Google account (optional, required for Premium)',
    prereq3: 'Internet connection for translation',
    install_title: 'Installation',
    install1: 'Open the Chrome Web Store and search for "Reborn Vision"',
    install2: 'Click "Add to Chrome" then "Add extension"',
    install3: 'Pin the icon in the Chrome toolbar',
    install4: 'Click the icon to open the Vision panel',
    free_title: 'Free version',
    free1: '5 translations per day',
    free2: '1 active capture zone',
    free3: 'Ctrl+E shortcut to activate zone selector',
    free4: '6 visual themes available',
    premium_title: 'Premium version',
    premium1: 'Sign in with Google from the Premium tab',
    premium2: 'Choose your plan (monthly / yearly / lifetime)',
    premium3: 'Unlimited translations on unlimited zones',
    premium4: 'Activate Watch Mode on any zone'
  },
  features_page: {
    title: 'Features',
    free_title: 'Free',
    premium_title: 'Premium',
    f_free1: 'OCR on 1 active zone',
    f_free2: '5 translations / day',
    f_free3: '15 translation languages',
    f_free4: '6 visual themes',
    f_free5: '15-language interface',
    f_free6: 'Ctrl+E shortcut',
    f_prem1: 'Unlimited zones',
    f_prem2: 'Unlimited translations',
    f_prem3: 'Automatic Watch Mode',
    f_prem4: 'Re-translation when text changes',
    f_prem5: 'Priority support',
    f_prem6: 'Access to future features'
  },
  interface_page: {
    title: 'Interface & Customization',
    themes_title: '6 visual themes',
    theme1: 'MMO Gold',
    theme2: 'Cyber Blue',
    theme3: 'Neon Purple',
    theme4: 'Fire Red',
    theme5: 'Dark',
    theme6: 'White',
    langs_title: '15 interface languages',
    shortcuts_title: 'Keyboard shortcuts',
    shortcut1_key: 'Ctrl+E',
    shortcut1_desc: 'Activate zone selector'
  },
  troubleshooting: {
    title: 'Troubleshooting',
    ocr_title: 'Inaccurate OCR',
    ocr1: 'Increase the size of the captured zone',
    ocr2: 'Make sure the text is sharp and readable',
    ocr3: 'Avoid zones with too much animated background',
    nozone_title: 'Zone not responding',
    nozone1: 'Reload the page and try again',
    nozone2: 'Some sites block external scripts (e.g. Google Docs)',
    nozone3: 'Check that the extension is enabled on this site',
    limit_title: 'Daily limit reached',
    limit1: 'The 5 translations/day limit resets at midnight',
    limit2: 'Go Premium for unlimited translations'
  },
  privacy_page: {
    title: 'Legal & Privacy',
    disclaimer_title: 'Disclaimer',
    disclaimer_text: 'Reborn Vision is provided "as is" without warranty of any kind. Use of this extension must comply with the terms of service of the websites visited. The publisher disclaims all liability for non-compliant use.',
    license_title: 'License',
    license_text: 'Personal, non-exclusive, non-transferable license. Redistribution, resale, or reverse engineering are prohibited. The publisher reserves the right to terminate access in case of violation.',
    privacy_title: 'Privacy',
    privacy_free: 'Free version: no data collection.',
    privacy_premium: 'Premium version: email and device ID stored in Firebase (Google Cloud) for license management.',
    privacy_images: 'Screenshots are processed in real time and never stored.',
    privacy_no: 'No browsing logs. No advertising tracking. No data sold.',
    gdpr_title: 'GDPR',
    gdpr_text: 'In accordance with GDPR, you have rights of access, rectification, deletion, and portability. Contact: seymoon.cell@gmail.com. Data retention: up to 30 days after subscription ends.',
    third_title: 'Third-party services',
    third_text: 'Google OAuth2 (authentication), Stripe (payments), Firebase (account storage). No other third party has access to your data.',
    contact_title: 'Contact',
    contact_text: 'For any questions: seymoon.cell@gmail.com'
  }
};
