// © 2026 Reborn Vision — All rights reserved. Unauthorized copying, modification or distribution is strictly prohibited. https://reborn-vision.com
export default {
  nav: {
    docs: 'Documentation',
    manage: 'Gérer mon abonnement',
    install: 'Installer gratuitement'
  },
  hero: {
    badge: 'Traduction OCR en temps réel',
    title: 'REBORN VISION',
    tagline: 'Traduisez n\'importe quel texte à l\'écran. En temps réel.',
    sub: 'Sélectionnez une zone, appuyez sur Ctrl+E — la traduction apparaît instantanément. Fonctionne sur tous les sites, tous les jeux, toutes les images.',
    cta_primary: 'Installer gratuitement',
    cta_secondary: 'Voir la documentation',
    trust1: '5 traductions/jour gratuites',
    trust2: 'Aucune donnée stockée',
    trust3: '15 langues OCR',
    store_name: 'Chrome Web Store',
    store_sub: 'Extension gratuite',
    store_rating: '★★★★★'
  },
  features: {
    title: 'Tout ce dont vous avez besoin',
    sub: 'Une extension pensée pour la fluidité — traduire ne doit pas interrompre votre expérience.',
    f1_title: 'OCR universel',
    f1_desc: 'Capture et lit le texte de n\'importe quelle zone d\'écran : sous-titres, interfaces de jeu, PDF, images. Si c\'est affiché, Vision peut le lire.',
    f1_badge: 'Toutes langues',
    f2_title: 'Traduction instantanée',
    f2_desc: 'La bulle de traduction apparaît directement sur votre écran, au bon endroit, sans quitter la page ni ouvrir d\'onglet.',
    f2_badge: 'Sans friction',
    f3_title: 'Watch Mode',
    f3_desc: 'Activez le mode surveillance sur une zone — Vision re-traduit automatiquement dès que le texte change. Parfait pour les sous-titres live.',
    f3_badge: 'Premium',
    f4_title: 'Multi-zones',
    f4_desc: 'Définissez plusieurs zones de capture simultanées sur la même page. Chaque zone a sa propre bulle de traduction.',
    f4_badge: 'Premium',
    f5_title: 'Interface personnalisable',
    f5_desc: '6 thèmes visuels (MMO Gold, Cyber Blue, Neon Purple, Fire Red, Dark, White). Choisissez celui qui correspond à votre setup.',
    f5_badge: 'Gratuit',
    f6_title: '15 langues d\'interface',
    f6_desc: 'L\'interface de Vision est disponible en 15 langues. Configurez une fois, utilisez partout.',
    f6_badge: 'Gratuit'
  },
  security: {
    title: 'Conçu pour la confidentialité',
    sub: 'Vos captures ne sont jamais stockées. Les images sont traitées en temps réel et immédiatement supprimées.',
    s1_title: 'Authentification sécurisée',
    s1_desc: 'Connexion via Google OAuth2. Jetons JWT avec expiration courte, aucun mot de passe stocké.',
    s2_title: 'Paiements Stripe',
    s2_desc: 'Transactions 100% gérées par Stripe. Nous ne voyons jamais votre numéro de carte.',
    s3_title: 'Zéro tracking',
    s3_desc: 'Aucun historique de navigation collecté. Aucune donnée personnelle vendue ou partagée.',
    s4_title: 'Images jamais stockées',
    s4_desc: 'Les captures de zones sont traitées en temps réel sur nos serveurs sécurisés et immédiatement supprimées après traitement.'
  },
  pricing: {
    title: 'Choisissez votre plan',
    sub: 'Commencez gratuitement. Passez premium quand vous êtes prêt.',
    popular: 'Populaire',
    per_month: '/mois',
    per_year: '/an',
    one_time: 'paiement unique',
    trial: 'Essai gratuit 7 jours',
    cta_free: 'Commencer gratuitement',
    cta_paid: 'Commencer l\'essai',
    cta_lifetime: 'Obtenir à vie',
    voyageur: {
      rank: 'Voyageur',
      price: '0€',
      f1: '5 traductions par jour',
      f2: '1 zone active',
      f3: '15 langues OCR',
      f4: '6 thèmes visuels',
      f5: 'Interface 15 langues'
    },
    aventurier: {
      rank: 'Aventurier',
      price: '2,99€',
      f1: 'Traductions illimitées',
      f2: 'Zones illimitées',
      f3: 'Watch Mode automatique',
      f4: 'Support prioritaire',
      f5: 'Accès anticipé nouveautés'
    },
    champion: {
      rank: 'Champion',
      price: '24,99€',
      save: 'Économisez 30%',
      f1: 'Traductions illimitées',
      f2: 'Zones illimitées',
      f3: 'Watch Mode automatique',
      f4: 'Support prioritaire',
      f5: 'Accès anticipé nouveautés'
    },
    legende: {
      rank: 'Légende',
      price: '99,99€',
      f1: 'Traductions illimitées à vie',
      f2: 'Zones illimitées',
      f3: 'Watch Mode automatique',
      f4: 'Toutes les futures fonctionnalités',
      f5: 'Support prioritaire à vie'
    }
  },
  faq: {
    title: 'Questions fréquentes',
    q1: 'Est-ce que Vision fonctionne sur tous les sites ?',
    a1: 'Oui. Vision s\'injecte sur tous les sites web. Si du texte est visible à l\'écran, Vision peut le capturer et le traduire — même dans les jeux via navigateur, les PDF, ou les images.',
    q2: 'Comment fonctionne l\'OCR ?',
    a2: 'Vous sélectionnez une zone avec Ctrl+E, Vision capture cette zone et l\'envoie à nos serveurs sécurisés pour reconnaissance de texte (OCR). La traduction est renvoyée en moins d\'une seconde. Les images ne sont jamais stockées.',
    q3: 'Puis-je annuler mon abonnement ?',
    a3: 'Oui, à tout moment depuis le portail client Stripe. L\'accès Premium est maintenu jusqu\'à la fin de la période payée. Aucun frais caché.',
    q4: 'Le plan à vie inclut-il les futures fonctionnalités ?',
    a4: 'Oui. Le plan Légende donne accès à toutes les fonctionnalités actuelles et futures, sans limitation dans le temps.',
    q5: 'Mes données sont-elles sécurisées ?',
    a5: 'Les captures d\'écran sont traitées en temps réel et jamais stockées. Seuls votre email et statut d\'abonnement sont conservés dans Firebase. Aucune donnée de navigation n\'est collectée.'
  },
  stats: {
    s1: '15 langues',
    s1_sub: 'Langues OCR supportées',
    s2: '6 thèmes',
    s2_sub: 'Thèmes visuels',
    s3: 'Temps réel',
    s3_sub: 'Traduction instantanée',
    s4: '0 stockage',
    s4_sub: 'Images jamais conservées'
  },
  trust: {
    t1: 'Paiement sécurisé Stripe',
    t2: 'Annulation à tout moment',
    t3: 'Essai gratuit 7 jours',
    t4: 'Support réactif'
  },
  footer: {
    tagline: 'Traduction OCR en temps réel pour Chrome.',
    docs: 'Documentation',
    legal: 'Mentions légales',
    privacy: 'Confidentialité',
    contact: 'Contact',
    rights: '© 2026 Reborn Vision. Tous droits réservés.'
  },
  docs: {
    home_title: 'Documentation',
    home_sub: 'Tout ce que vous devez savoir pour utiliser Reborn Vision.',
    cat_user: 'Guide utilisateur',
    cat_support: 'Support',
    cat_legal: 'Informations légales',
    card_quickstart_title: 'Démarrage rapide',
    card_quickstart_desc: 'Installez Vision, sélectionnez votre première zone et faites votre première traduction en 2 minutes.',
    card_features_title: 'Fonctionnalités',
    card_features_desc: 'Comparatif complet Gratuit vs Premium. Watch Mode, multi-zones, raccourcis.',
    card_interface_title: 'Interface & Personnalisation',
    card_interface_desc: 'Thèmes, langues, paramètres avancés, raccourcis clavier.',
    card_troubleshooting_title: 'Dépannage',
    card_troubleshooting_desc: 'Problèmes courants et solutions. OCR imprécis, zone qui ne répond pas, etc.',
    card_privacy_title: 'Légal & Confidentialité',
    card_privacy_desc: 'Politique de confidentialité, conditions d\'utilisation, RGPD, licence.'
  },
  quickstart: {
    title: 'Démarrage rapide',
    prereq_title: 'Prérequis',
    prereq1: 'Navigateur Chromium (Chrome, Edge, Brave...)',
    prereq2: 'Compte Google (optionnel, requis pour Premium)',
    prereq3: 'Connexion internet pour la traduction',
    install_title: 'Installation',
    install1: 'Ouvrez le Chrome Web Store et cherchez "Reborn Vision"',
    install2: 'Cliquez sur "Ajouter à Chrome" puis "Ajouter l\'extension"',
    install3: 'Épinglez l\'icône dans la barre d\'outils Chrome',
    install4: 'Cliquez sur l\'icône pour ouvrir le panneau Vision',
    free_title: 'Version gratuite',
    free1: '5 traductions par jour',
    free2: '1 zone de capture active',
    free3: 'Raccourci Ctrl+E pour activer le sélecteur de zone',
    free4: '6 thèmes visuels disponibles',
    premium_title: 'Version Premium',
    premium1: 'Connectez-vous avec Google depuis l\'onglet Premium',
    premium2: 'Choisissez votre plan (mensuel / annuel / à vie)',
    premium3: 'Traductions illimitées sur zones illimitées',
    premium4: 'Activez le Watch Mode sur n\'importe quelle zone'
  },
  features_page: {
    title: 'Fonctionnalités',
    free_title: 'Gratuit',
    premium_title: 'Premium',
    f_free1: 'OCR sur 1 zone active',
    f_free2: '5 traductions / jour',
    f_free3: '15 langues de traduction',
    f_free4: '6 thèmes visuels',
    f_free5: 'Interface en 15 langues',
    f_free6: 'Raccourci Ctrl+E',
    f_prem1: 'Zones illimitées',
    f_prem2: 'Traductions illimitées',
    f_prem3: 'Watch Mode automatique',
    f_prem4: 'Re-traduction si texte change',
    f_prem5: 'Support prioritaire',
    f_prem6: 'Accès aux futures fonctionnalités'
  },
  interface_page: {
    title: 'Interface & Personnalisation',
    themes_title: '6 thèmes visuels',
    theme1: 'MMO Gold',
    theme2: 'Cyber Blue',
    theme3: 'Neon Purple',
    theme4: 'Fire Red',
    theme5: 'Dark',
    theme6: 'White',
    langs_title: '15 langues d\'interface',
    shortcuts_title: 'Raccourcis clavier',
    shortcut1_key: 'Ctrl+E',
    shortcut1_desc: 'Activer le sélecteur de zone'
  },
  troubleshooting: {
    title: 'Dépannage',
    ocr_title: 'OCR imprécis',
    ocr1: 'Augmentez la taille de la zone capturée',
    ocr2: 'Assurez-vous que le texte est net et lisible',
    ocr3: 'Évitez les zones avec trop d\'arrière-plan animé',
    nozone_title: 'La zone ne répond pas',
    nozone1: 'Rechargez la page et réessayez',
    nozone2: 'Certains sites bloquent les scripts externes (ex: Google Docs)',
    nozone3: 'Vérifiez que l\'extension est bien activée sur ce site',
    limit_title: 'Limite quotidienne atteinte',
    limit1: 'La limite de 5 traductions/jour se réinitialise à minuit',
    limit2: 'Passez Premium pour des traductions illimitées'
  },
  privacy_page: {
    title: 'Légal & Confidentialité',
    disclaimer_title: 'Avertissement',
    disclaimer_text: 'Reborn Vision est fourni "tel quel" sans garantie d\'aucune sorte. L\'utilisation de cette extension doit respecter les conditions d\'utilisation des sites visités. L\'éditeur décline toute responsabilité en cas d\'utilisation non conforme.',
    license_title: 'Licence',
    license_text: 'Licence personnelle, non-exclusive, non-transférable. La redistribution, la revente ou l\'ingénierie inverse sont interdites. L\'éditeur se réserve le droit de résilier l\'accès en cas de violation.',
    privacy_title: 'Confidentialité',
    privacy_free: 'Version gratuite : aucune collecte de données.',
    privacy_premium: 'Version Premium : email et identifiant d\'appareil stockés dans Firebase (Google Cloud) pour la gestion de licence.',
    privacy_images: 'Les captures d\'écran sont traitées en temps réel et jamais stockées.',
    privacy_no: 'Aucun log de navigation. Aucun tracking publicitaire. Aucune donnée vendue.',
    gdpr_title: 'RGPD',
    gdpr_text: 'Conformément au RGPD, vous disposez des droits d\'accès, de rectification, de suppression et de portabilité. Contact : seymoon.cell@gmail.com. Rétention des données : jusqu\'à 30 jours après la fin de l\'abonnement.',
    third_title: 'Services tiers',
    third_text: 'Google OAuth2 (authentification), Stripe (paiements), Firebase (stockage compte). Aucun autre tiers n\'a accès à vos données.',
    contact_title: 'Contact',
    contact_text: 'Pour toute question : seymoon.cell@gmail.com'
  }
};
